language: objective-c
osx_image: xcode9.3


env:
  global:
  - LANG=en_US.UTF-8
  - PROJECT="mamba.xcodeproj"
  - IOS_SCHEME="mamba"
  - TVOS_SCHEME="mambaTVOS"
  - IOS_SDK=iphonesimulator11.0
  - TVOS_SDK=appletvsimulator11.0
  matrix:
  #- DESTINATION="OS=9.3,name=iPhone 6"               SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"
  #- DESTINATION="OS=9.3,name=iPad Air"               SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"

  #- DESTINATION="OS=10.1,name=iPhone 7"              SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"
  #- DESTINATION="OS=10.2,name=iPad Air 2"            SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"

  - DESTINATION="OS=11.1,name=iPhone X"              SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"
  #- DESTINATION="OS=11.1,name=iPad Pro (10.5-inch)"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"

  - DESTINATION="OS=11.1,name=Apple TV 4K"           SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME" RUN_TESTS="YES"

script:
  - set -o pipefail
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    else
      xcodebuild build analyze -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi
    
after_success:
  - bash <(curl -s https://codecov.io/bash)